/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HistoryIndexImport } from './routes/history/index'
import { Route as CreatorIndexImport } from './routes/creator/index'
import { Route as CategoriesIndexImport } from './routes/categories/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryIndexRoute = HistoryIndexImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRoute,
} as any)

const CreatorIndexRoute = CreatorIndexImport.update({
  id: '/creator/',
  path: '/creator/',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesIndexRoute = CategoriesIndexImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/creator/': {
      id: '/creator/'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorIndexImport
      parentRoute: typeof rootRoute
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/history': typeof HistoryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/history': typeof HistoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/history/': typeof HistoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categories' | '/creator' | '/history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categories' | '/creator' | '/history'
  id: '__root__' | '/' | '/categories/' | '/creator/' | '/history/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CreatorIndexRoute: CreatorIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/categories/",
        "/creator/",
        "/history/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/categories/": {
      "filePath": "categories/index.tsx"
    },
    "/creator/": {
      "filePath": "creator/index.tsx"
    },
    "/history/": {
      "filePath": "history/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
